# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97e7018602985f616c8d50a823050b3d15f33d8023759ed31d7412f52e7cae0886a77a6d5dd7dea62da1ee7e8e2127d9d8b8fe09cdc3c3ab76f0a66cbf3f36dd

test:
  secret_key_base: 3ab0076d62e4c185ad91ace80f4d9fdcd3a536dc48863aceccb217feed88769279f6d6002eec24951068e637060bb6223c6097404df432b9797763a85e87c461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
